### ISSUE TITLE
Worldly Hex Package ETA?

### ISSUE THREAD

**Issue by samhamilton** [vinsol/nectarcommerce#73]
Hey! 

I was just wondering when you will be releasing the Worldly package on Hex? Even if its just v0.0.1

Cheers
Sam

**Comment by samhamilton** [comment]
Actually even if Worldly was its own github repo that would help too, then I could install it as a dep in my mix file `{:worldly, github: "vinsol/worldly"}`

Thanks
Sam

**Comment by pikender** [comment]
@samhamilton , worldly code is now available at https://github.com/vinsol/worldly

We are making changes for its release and should be available soon on hex.

To use it till package work is in progress, please use below deps representation in your mix.exs to use it independently

``` exs
{:worldly, github: "vinsol/worldly", branch: "from/nectar"}
```

Let us know, if you face any problems and create an issue on worldly repo https://github.com/vinsol/worldly/issues

Thanks for the suggestion and interest in use of worldly :)

**Comment by samhamilton** [comment]
many thanks @pikender !

**Comment by pikender** [comment]
@samhamilton we have a released a hex package too https://hex.pm/packages/worldly

Check the installation steps [here](https://github.com/vinsol/worldly#installation) and let me know, if you face any issues

**Comment by samhamilton** [comment]
@pikender Many thanks!
