### ISSUE TITLE
submenu of the navigation bar in admin page did not work 

### ISSUE THREAD

**Issue by toreal** [vinsol/nectarcommerce#84]
such as Product/setting/zone/...

if I was at the admin-home page,  when I click the products menu
http://localhost:4000/admin
It just goto
http://localhost:4000/admin#
nothing happened.

BTW, thank you for providing the source code for learning. But, I found the demo site sometimes can not login. Maybe someone changes the password. Additionally, Docker image can not run after it syncs the newest version.

**Comment by pikender** [comment]
@toreal I checked `http://localhost:4000/admin`, links are working as expected ☺️ 

Can you try building your assets again `cd apps/nectar && ./node_modules/brunch/bin/brunch build` ?

Also, share any error you might be seeing in Browser Console, it would help resolving the issue on your system.

Try the admin end on [Demo Server](http://nectarcommerce.vinsol.com/admin) with credentials `bob@example.com` / `secured` as mentioned in README [here](https://github.com/vinsol/nectarcommerce#demo)

Docker image work is in progress and will be available soon 👍

**Comment by toreal** [comment]
I did not see any error message. Also, I have selected the dropdown part of the code and tested it.  It works fine.   
I saw a similar situation as following. 

[http://stackoverflow.com/questions/22383547/bootstrap-dropdown-menu-is-not-working](http://stackoverflow.com/questions/22383547/bootstrap-dropdown-menu-is-not-working)

But I don't know how to check it

**Comment by toreal** [comment]
Thank you my hero.

after install and build with following commands. everything is fine now.

npm install -g bower
bower install 
node node_modules/brunch/bin/brunch build

**Comment by pikender** [comment]
Yeyy !! Happy to hear that you resolved it :100: :+1: :relaxed:
